server:
  port: 9998
  servlet:
    # 上传文件大小限制，默认1M
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

spring:
# rabbitmq
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
#    publisher-confirms: true
    publisher-confirm-type: correlated
    publisher-returns: true
    # 虚拟host，需要控制台配置
    virtual-host: /rabbitmq_demo

  data:
    mongodb:
      # 如果uri最后不跟具体的db，则这个账号表示admin下（source=admin）
      uri: mongodb://127.0.0.1:27017/tool
#      uri: mongodb://tool:tool@127.0.0.1:27017/tool
#            uri: mongodb://tool:tool@172.31.10.64:27017/tool

#            uri: mongodb://127.0.0.1/tool
#            port: 27017
#            username: kunbu
#            password: 123456
      options:
        min-connections-per-host: 20
        max-connections-per-host: 20
        threads-allowed-to-block-for-connection-multiplier: 5
        server-selection-timeout: 30000
        max-wait-time: 120000
        max-connection-idel-time: 0
        max-connection-life-time: 0
        connect-timeout: 10000
        socket-timeout: 0
        socket-keep-alive: false
        ssl-enabled: false
        ssl-invalid-host-name-allowed: false
        always-use-m-beans: false
        heartbeat-socket-timeout: 20000
        heartbeat-connect-timeout: 20000
        min-heartbeat-frequency: 500
        heartbeat-frequency: 10000
        local-threshold: 15
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
# 以下是mybatis-plus双数据源
      biz:
        url: jdbc:mysql://127.0.0.1:3306/scosyf?useUnicode=true&allowMultiQueries=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai&useAffectedRows=true
#        url: jdbc:log4jdbc:mysql://127.0.0.1:3306/scosyf?useUnicode=true&allowMultiQueries=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai&useAffectedRows=true
        username: root
        password: 930628
#        password:
#        driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
        driver-class-name: com.mysql.cj.jdbc.Driver
      mybatis:
        url: jdbc:mysql://127.0.0.1:3306/mybatis?useUnicode=true&allowMultiQueries=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai&useAffectedRows=true
        username: root
        password: 930628
#        password:
        driver-class-name: com.mysql.cj.jdbc.Driver
# 以下是jpa双数据源
      quartz:
        url: jdbc:mysql://127.0.0.1:3306/quartz?useUnicode=true&allowMultiQueries=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai&useAffectedRows=true
        username: root
        password: 930628
        #      password:
        driver-class-name: com.mysql.cj.jdbc.Driver
      jpa:
        url: jdbc:mysql://127.0.0.1:3306/jpa?useUnicode=true&allowMultiQueries=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai&useAffectedRows=true
        username: root
        password: 930628
        #      password:
        driver-class-name: com.mysql.cj.jdbc.Driver

      initial-size: 10
      max-active: 30
      max-open-prepared-statements: 20
      max-wait: 60000
      min-evictable-idle-time-millis: 30000
      min-idle: 10
      log-abandoned: true
      remove-abandoned: true
      remove-abandoned-timeout: 1800
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      time-between-eviction-runs-millis: 60000
      # 验证数据库连接的查询语句
      validation-query: SELECT 1
      # 合并多个DruidDataSource的监控数据
      useGlobalDataSourceStat: true
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，wall用于防火墙
      filters: stat
      # 慢SQL日志
      filter:
        stat:
        enabled: true
        log-slow-sql: true
        slow-sql-millis: 1

# redis双数据源
  redis:
#    host: 127.0.0.1 # RedisProperties
    hostName: 127.0.0.1 # RedisStandaloneConfiguration
    port: 6379
#    password: #redis
    password: '123456'
    # 默认是索引为0的数据库
    database: 1
    # 连接池最大阻塞等待时间（使用负值表示没有限制）
    lettuce:
      pool:
        max-wait: 200
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 100
        # 连接池中的最大空闲连接
        max-idle: 20
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接超时时间（毫秒）
        timeout: 5000
  redis2:
    hostName: 127.0.0.1
    port: 6379
#    password: #redis
    password: '123456'
    database: 2

  quartz:
    # 数据库方式
    job-store-type: JDBC
    #初始化表结构
    jdbc:
#      initialize-schema: always
      initialize-schema: never
    # 相关属性配置
    properties:
      org:
        quartz:
          scheduler:
            instanceName: quartzScheduler
            instanceId: AUTO
          jobStore:
            class: org.quartz.impl.jdbcjobstore.JobStoreTX
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            tablePrefix: qrtz_
            isClustered: false
            clusterCheckinInterval: 10000
            useProperties: false
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            # 线程数 一个任务使用一个线程
            threadCount: 100
            threadPriority: 5
            threadsInheritContextClassLoaderOfInitializingThread: true

  mail:
#    host: smtp.qq.com
    host: smtp.163.com
    username: 18806719815@163.com
    password: syf930628
    port: 465
    default-encoding: utf-8
#    protocol: smtp
    properties:
#      mail.debug: true
      mail.smtp.auth: true
      mail.smtp.timeout: 25000
      mail.smtp.ssl.enable: true
      mail.smtp.starttls.enable: false
      mail.smtp.socketFactory.fallback: false
      mail.smtp.socketFactory.class: javax.net.ssl.SSLSocketFactory


exception:
  mail:
    to: 1274462659@qq.com,syf1274462659@163.com

img:
  sticker: common/img/template.png

logging:
  config: classpath:log4j2.xml

#sms config
sms:
  appId: EUCP-EMY-SMS1-2XW5H
  secretKey: 2020AEC0E3350FDA

# mail 原生配置，需要手动读取并配置 JavaMailSenderImpl
mail:
  host: smtp.163.com
  username: 18806719815@163.com
  password: syf930628
  port: 465
  properties:
    mail.smtp.auth: true
    mail.smtp.timeout: 25000
    mail.smtp.ssl.enable: true
    mail.smtp.starttls.enable: false
    mail.smtp.socketFactory.fallback: false
    mail.smtp.socketFactory.class: javax.net.ssl.SSLSocketFactory

qiniu:
  accessKey: SHbatWUfOdBBbR_Nzk_0NcAtFhU84bs9V_x-EMGU
  secretKey: 0Tye20o0GShSIhbNOWY7bQyeb8s19DsuksuroCQq
  bucket: xj-yun-bucket
  url: s.y.xiaojiang.cc