spring:
  redis:
    host: localhost
    # Redis服务器连接端口
    port: 6379
    password:
    #默认是索引为0的数据库
    database: 1
    # 连接超时时间（毫秒）
    timeout: 5000ms
    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 100
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 100000ms
        # 连接池中的空闲连接
        max-idle: 10
        min-idle: 0

  data:
    mongodb:
      uri: mongodb://localhost/tool
      port: 27017
      username: kunbu
      password: 123456

  mail:
#    host: smtp.qq.com
    host: smtp.163.com
    username: 18806719815@163.com
    password: syf930628
    port: 465
    default-encoding: utf-8
#    protocol: smtp
    properties:
#      mail.debug: true
      mail.smtp.auth: true
      mail.smtp.timeout: 25000
      mail.smtp.ssl.enable: true
      mail.smtp.starttls.enable: false
      mail.smtp.socketFactory.fallback: false
      mail.smtp.socketFactory.class: javax.net.ssl.SSLSocketFactory

# 上传文件大小限制，默认1M
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

exception:
  mail:
    to: 1274462659@qq.com,syf1274462659@163.com

img:
  sticker: demo/img/template.png

server:
  port: 9999

logging:
  config: classpath:log4j2.xml

#sms config
sms:
  appId: EUCP-EMY-SMS1-2XW5H
  secretKey: 2020AEC0E3350FDA

# mail 原生配置，需要手动读取并配置 JavaMailSenderImpl
mail:
  host: smtp.163.com
  username: 18806719815@163.com
  password: syf930628
  port: 465
  properties:
    mail.smtp.auth: true
    mail.smtp.timeout: 25000
    mail.smtp.ssl.enable: true
    mail.smtp.starttls.enable: false
    mail.smtp.socketFactory.fallback: false
    mail.smtp.socketFactory.class: javax.net.ssl.SSLSocketFactory
