server:
  port: 9999

logging:
  config: classpath:log4j2.xml

spring:
  data:
    mongodb:
      uri: mongodb://localhost/tool
      port: 27017
      username: kunbu
      password: 123456
  mail:
#    host: smtp.qq.com
    host: smtp.163.com
    username: 18806719815@163.com
    password: syf930628
    port: 465
    default-encoding: utf-8
#    protocol: smtp
    properties:
#      mail.debug: true
      mail.smtp.auth: true
      mail.smtp.timeout: 25000
      mail.smtp.ssl.enable: true
      mail.smtp.starttls.enable: false
      mail.smtp.socketFactory.fallback: false
      mail.smtp.socketFactory.class: javax.net.ssl.SSLSocketFactory
# 上传文件大小限制，默认1M
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

exception:
  mail:
    to: 1274462659@qq.com,syf1274462659@163.com

img:
  sticker: demo/img/template.png



# mail 原生配置，需要手动读取并配置 JavaMailSenderImpl
mail:
  host: smtp.163.com
  username: 18806719815@163.com
  password: syf930628
  port: 465
  properties:
    mail.smtp.auth: true
    mail.smtp.timeout: 25000
    mail.smtp.ssl.enable: true
    mail.smtp.starttls.enable: false
    mail.smtp.socketFactory.fallback: false
    mail.smtp.socketFactory.class: javax.net.ssl.SSLSocketFactory
