server:
  port: 9999
# log4j2
logging:
  config: classpath:log4j2.xml

spring:
  # email
  mail:
    host: smtp.163.com     # SMTP 服务器地址(smtp.qq.com)
    username: 18806719815@163.com
    password: syf930628
    port: 465
    default-encoding: utf-8
    # protocol: smtp
    properties:
      # mail.debug: true
      mail.smtp.auth: true
      mail.smtp.timeout: 25000
      mail.smtp.ssl.enable: true
      mail.smtp.starttls.enable: false
      mail.smtp.socketFactory.fallback: false
      mail.smtp.socketFactory.class: javax.net.ssl.SSLSocketFactory

  # mongodb
  data:
    mongodb:
      uri: mongodb://localhost/bucks
      port: 27017
      username: kunbu
      password: 123456


exception:
  mail:
    to: 1274462659@qq.com,syf1274462659@163.com







# mail 原生配置，需要手动读取并配置 JavaMailSenderImpl
mail:
  #  host: smtp.qq.com
  host: smtp.163.com
  username: 18806719815@163.com
  password: syf930628
  port: 465
  properties:
    # mail.debug: true
    mail.smtp.auth: true
    mail.smtp.timeout: 25000
    mail.smtp.ssl.enable: true
    mail.smtp.starttls.enable: false
    mail.smtp.socketFactory.fallback: false
    mail.smtp.socketFactory.class: javax.net.ssl.SSLSocketFactory
